version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y jq
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 890742579881.dkr.ecr.ap-south-1.amazonaws.com/django-app
      - echo "Authenticating to Amazon EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name my-cluster

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t django-app -f 6Dockerfile .
      - docker tag django-app:latest 890742579881.dkr.ecr.ap-south-1.amazonaws.com/django-app:latest
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 890742579881.dkr.ecr.ap-south-1.amazonaws.com/django-app:latest
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f mysql-deployment.yaml
      - kubectl apply -f redis-deployment.yaml
      - kubectl apply -f django-deployment.yaml

  post_build:
    commands:
      - echo "Deployment complete!"

artifacts:
  files: '**/*'
